services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  cmpt756db:
    build: ../db
    image: ci_db
    container_name: cmpt756db
    ports:
      - "30002:30002"
    environment:
      AWS_REGION: 'us-west-2'
      AWS_ACCESS_KEY_ID: 'DUMMY_KEY_ID'
      AWS_SECRET_ACCESS_KEY: 'DUMMY_ACCESS_KEY'
      SVC_LOADER_TOKEN: 'DUMMY_LOADER_TOKEN'
      DYNAMODB_URL: 'http://dynamodb-local:8000'
  cmpt756artist:
    depends_on:
      - dynamodb-local
      - cmpt756db
    build: ../artist
    image: ci_artist
    container_name: cmpt756artist
    ports:
      - "30003:30003"
  test:
    command: "pytest --user_address cmpt756user --user_port 30000 --music_address cmpt756music --music_port 30001 --artist_address cmpt756artist --artist_port 30003 --table_suffix interactive-tomato"
    depends_on:
      - dynamodb-local
      - cmpt756db
      - cmpt756artist
    build: ../test
    image: ci_test
    container_name: test
    environment:
      AWS_REGION: 'us-west-2'
      AWS_ACCESS_KEY_ID: 'DUMMY_KEY_ID'
      AWS_SECRET_ACCESS_KEY: 'DUMMY_ACCESS_KEY'
      SVC_LOADER_TOKEN: 'DUMMY_LOADER_TOKEN'
      DYNAMODB_URL: 'http://dynamodb-local:8000'